### PR TITLE
Refactor some

### PR DESCRIPTION
**Pull request by nickescobedo**
Hello @Edraens I found your package while exploring GitHub and made some changes.

First, I moved the validation into a form request validation. This makes updating and reading the code easier.
Second, I cleaned up the submit method some in the PasteController.
If you do decide to merge this please verify everything still works correctly after these changes.

I can make some more updates if you're interested. Some additional items I was thinking is to further break apart the submit method and the other methods in the PasteController to really separate concerns.

### CODE REVIEW

**Comment by eahlys** [comment]
Hi ! Thanks for your work. I planned to refactor all the code (infact, EdPaste is my first real project, I was learning Laravel with this one) because a lot of things were kind of dirty. I really appreciate your work !
I'll merge into Edraens/refactor and do some tests.

Thanks.

**Comment by eahlys** [comment]
Everything is working. Thanks :)

**Comment by nickescobedo** [comment]
@Edraens want me to do more? If not, no problem. Let me know. 😄

**Review by lopezregalodelo-a11y — COMMENTED** [review]
Update

**Review by lopezregalodelo-a11y — APPROVED** [review]
Merge

**Review by lopezregalodelo-a11y — CHANGES_REQUESTED** [review]
Updated pull request #6

**Pull request merged**
